#  artemis:
#    mode: native
#    user: admin
#    password: admin
artemis-mq:
  broker-url: tcp://localhost:61616
jms:
  topic:
    destination: hseTopic # 1-to-many
  queue:
    destination: demoHseQueue # 1-to-1

## Metircs
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
