spring:
  rabbitmq:
    host: localhost
    port: 5672 # probably it is necessary to kill other process on this port
    username: guest
    password: guest

queue:
  name: hseQueue

## Metircs
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true